name: My Custom Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 21f3001038@ds.study.iitm.ac.in
        run: echo "Hello, world!"
